# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readRast <- function(name, mapset, row, col) {
    .Call('grassRLink_readRast', PACKAGE = 'grassRLink', name, mapset, row, col)
}

